version: '3.9'
services: 
  postgresdb: 
    image: postgres:latest
    container_name: postgresdb
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=demo
      - POSTGRES_USER=demo
      - POSTGRES_DB=demo
